name: "ADC_emma_ghita"

on:
  push:
    branches: [ adc_ghita_emma ]

# job that builds linux kernel and dtb
jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm
  
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install -y gcc-arm-linux-gnueabi make bc flex bison libssl-dev u-boot-tools


      - name: Defconfig
        run: |
          make zynq_xcomm_adv7511_defconfig

      - name: Linux kernel
        run: |
          make -j$(nproc) UIMAGE_LOADADDR=0x8000 uImage
    
    # build device tree
      - name: Device tree
        run: |
          make xilinx/zynq-coraz7s-ad5592r-s.dtb
      
      - name: Upload linux kernel
        uses: actions/upload-artifact@v4
        with:
          name: uImage
          path: arch/arm/boot/uImage

      - name: Upload device tree
        uses: actions/upload-artifact@v4
        with:
          name: devicetree.dtb
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb

  checkpatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Run checkpatch
        run: |
          for commit in $(git rev-list origin/main..HEAD); do
            scripts/checkpatch.pl --git "$commit" --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict;
          done