name : Stanut Denisa ADC

on:
  push:
    branches: [ stanut_denisa_adc ]
    paths:
      - 'drivers/iio/adc/*'
      - '.github/workflows/adc_stanut_denisa.yml'
      - 'arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dts'

jobs:
  build-kernel:
    runs-on: denisa_stanut

    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install -y gcc-arm-linux-gnueabi make bc flex bison libssl-dev u-boot-tools

      - name: Defconfig
        run: |
          make zynq_xcomm_adv7511_defconfig

      - name: Build uImage
        run: |
          make -j12 UIMAGE_LOADADDR=0x8000 uImage

      - name: Device Tree
        run: |
          make xilinx/zynq-coraz7s-ad5592r-s.dtb


      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: uImage
          path: arch/arm/boot/uImage

      - name: Upload device tree
        uses: actions/upload-artifact@v4
        with:
          name: devicetree.dtb
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb

  check-patch:
    runs-on:
      denisa_stanut

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Fetch main branch
        run: git fetch origin main

      - name: Run checkpatch
        run: |
          for commit in $(git rev-list origin/main..HEAD); do
              scripts/checkpatch.pl --git "$commit" --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict;
            done

  build_coraz7:
    needs:
      build-kernel

    environment:
      summer_practice_secrets

    runs-on:
      denisa_stanut

    steps:
      - name: Download uImage
        uses: actions/download-artifact@v4
        with:
          name: uImage
          path: ./

      - name: Download device tree
        uses: actions/download-artifact@v4
        with:
          name: devicetree.dtb
          path: ./

      - name: Copy uImage and device tree
        run: |
          ls -l -R
          sshpass -p '${{ secrets.stanut_denisa_secret }}' scp -o StrictHostKeyChecking=no ./uImage root@10.76.84.24:/boot/
          sshpass -p '${{ secrets.stanut_denisa_secret }}' scp -o StrictHostKeyChecking=no ./zynq-coraz7s-ad5592r-s.dtb root@10.76.84.24:/boot/

      - name: Reboot the Cora Z7
        run: |
          sshpass -p '${{ secrets.stanut_denisa_secret }}' ssh -o StrictHostKeyChecking=no root@10.76.84.24 'reboot'