#Workflow name - appears in the Actions tab on GitHub
name: Emilia Pedolu ADC

on:
   push:
      branches: [emilia_pedolu_adc_feature]


jobs:
   checkpath:
      runs-on: emiliapedolu
      steps:
        - name: Checkout source
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Fetch main branch
          run: git fetch origin main

        - name: Run checkpath
          run: |
            for commit in $(git rev-list main..emilia_pedolu_adc_feature);do
              scripts/checkpatch.pl --git "$commit" --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict;
            done
          
   build-artifacts:
      runs-on: emiliapedolu

      env:
         CROSS_COMPILE: arm-linux-gnueabi-
         ARCH: arm
      
      steps: 
         - name: Checkout source
           uses: actions/checkout@v4
           with:
             fetch-depth: 1

         - name: Install
           run: |
             sudo apt-get -q update
             sudo apt-get install -y gcc-arm-linux-gnueabi make bc flex bison libssl-dev u-boot-tools

         - name: Build config
           run: |
             make zynq_xcomm_adv7511_defconfig

         - name: Build kernel
           run: |
             make -j$(nproc) UIMAGE_LOADADDR=0x8000 uImage

         - name: Build devicetree 
           run: |
             make xilinx/zynq-coraz7s-ad5592r-s.dtb
             
         - name: Upload uImage
           uses: actions/upload-artifact@v4
           with:
            name: upload_uImage
            path: arch/arm/boot/uImage

         - name: Upload devicetree
           uses: actions/upload-artifact@v4
           with:
            name: upload_devicetree
            path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb
