name: Flavius ADC Workflow

on:
  push:
    branches: [ moldovan_flavius_adc ]
    paths:
      - '.github/workflows/moldovan_flavius_adc.yml'
      - 'drivers/iio/adc/**'
      - 'arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dts'

jobs:
  build_uImage_and_dtb:
    runs-on: moldovan_flavius

    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm

    steps:
      - name: Checkout uImage & dtb source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup build environment
        run: |
          sudo apt-get -q update
          sudo apt-get install -y gcc-arm-linux-gnueabi make bc flex bison libssl-dev u-boot-tools

      - name: Produce artifact for uImage
        run: |
          make zynq_xcomm_adv7511_defconfig
          make -j$(nproc) UIMAGE_LOADADDR=0x8000 uImage

      - name: Produce artifact for dtb
        run: |
          make xilinx/zynq-coraz7s-ad5592r-s.dtb

      - name: Upload uImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: uImage-kernel
          path: arch/arm/boot/uImage

      - name: Upload dtb artifact
        uses: actions/upload-artifact@v4
        with:
          name: dtb-kernel
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb

  checkpatch:
    runs-on: moldovan_flavius_2

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: checkpatch run for each commit
        run: |
          scripts/checkpatch.pl --git HEAD --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict
          # COMMITS=$(git log --reverse --format="%H" origin/main..HEAD)
          # for commit in $COMMITS; do
            # scripts/checkpatch.pl --git "$commit" --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict
          # done

  deploy:
    needs: build_uImage_and_dtb
    environment: summer_practice_secrets
    runs-on: moldovan_flavius

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./

      - name: Display structure of downloaded files
        run: ls -l ./

      - name: Put device tree and uImage on coraz7s
        run: |
          sshpass -p '${{ secrets.moldovan_flavius_secret }}' scp -o StrictHostKeyChecking=no ./uImage-kernel/uImage root@10.76.84.04:/boot/
          sshpass -p '${{ secrets.moldovan_flavius_secret }}' scp -o StrictHostKeyChecking=no ./dtb-kernel/zynq-coraz7s-ad5592r-s.dtb root@10.76.84.04:/boot/devicetree.dtb

      - name: Reboot the Cora Z7
        run: |
          sshpass -p '${{ secrets.moldovan_flavius_secret }}' ssh -o StrictHostKeyChecking=no root@10.76.84.04 'sudo reboot'