name: Molnar_Levente_adc_ad5592r
on:
  push:
    branches: [ Molnar_Levente_adc ]
jobs:
  demo-workflow:
    runs-on: Molnar_Levente_adc_7
    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Built config
        run: |
          make versatile_adi_defconfig
      - name: Build kernel
        run: |
          make -j$(nproc) UIMAGE_LOADADDR=0x8000 uImage
      - name: Build device tree
        run: |
          make xilinx/zynq-coraz7s-ad5592r-s.dtb
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uImage
          path: arch/arm/boot/uImage
      - name: Upload dtb
        uses: actions/upload-artifact@v4
        with:
          name: zynq-coraz7s-ad5592r-s.dtb
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb
  run_checkpatch:
    runs-on: Molnar_Levente_adc_7
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find all commits and checkpatch them
        run: |
          git fetch origin main
          scripts/checkpatch.pl --git HEAD --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict
          #for commit in $(git log --format=%H HEAD --not origin/main); do
  deploy:
    runs-on: Molnar_Levente_adc_7
    needs: demo-workflow
    environment: summer_practice_secrets
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
      - name: Push artifacts to board
        run: |
          sudo apt-get install -y sshpass
          sshpass -p '${{ secrets.your_secret }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null out/uImage/uImage root@10.76.84.10:/root/
          sshpass -p '${{ secrets.your_secret }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null out/dtb/zynq-coraz7s-ad5592r-s.dtb root@10.76.84.10:/boot/devicetree.dtb