#First CI/CD Pipeline YaY

name : Papp Richard Workflow

on:
  push:
    branches: [PappRichard_ADC]
    paths:
      - "drivers/iio/adc/**"
      - "arch/arm/boot/uImage"
      - ".github/workflows/Workflow_Papp_Richard.yaml"
      - "arch/arm/boot/dts/xilinx/-"
  workflow_dispatch:
jobs:

  build_pyramids:
    runs-on : container_ricsi

    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm

    steps:

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure the environment
        run: |
          make zynq_xcomm_adv7511_defconfig

      - name: Build the image
        run: |
          make -j$(nproc) UIMAGE_LOADADDR=0x8000 uImage

      - name: Build the devicetree
        run: |
          make xilinx/zynq-coraz7s-ad5592r_s.dtb

      - name: Mark it in hieroglyphs
        uses: actions/upload-artifact@v4
        with:
          name: uImage
          path: arch/arm/boot/uImage

      - name: Paint the papyruses
        uses: actions/upload-artifact@v4
        with:
          name: devicetree.dtb
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r_s.dtb

  vibe-based-style-check:

    runs-on : papp_richard

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Vibe-check
        run: |
          for commit in $(git log origin/main..HEAD --format='%h');
            do
              scripts/checkpatch.pl --git "$commit" --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --strict;
            done

  where_we_dropin:
    environment: summer_practice_secrets

    needs: build_pyramids

    runs-on: papp_richard_tf

    steps:
      - name: Getting over it
        uses: actions/download-artifact@v8
        with:
          name: uImage

      - name: Getting ahead
        uses: actions/download-artifact@v8
        with:
          name: devicetree.dtb

      - name: Getting there
        run: |
          sshpass -p '${{ secrets.secret_of_papp_richard }}' scp -o StrictHostKeyChecking=no zynq-coraz7s-ad5592r_s.dtb root@10.76.84.21:/boot/devicetree.dtb
          sshpass -p '${{ secrets.secret_of_papp_richard }}' scp -o StrictHostKeyChecking=no uImage root@10.76.84.21:/boot/

      - name: Getting it done
        run: |
          sshpass -p '${{ secrets.secret_of_papp_richard }}' ssh -o StrictHostKeyChecking=no root@10.76.84.21 'sudo reboot'