
name:  berinde_codrin_adc

on:
  push:
    branches: [berinde_codrin_adc]
    paths:
      - 'drivers/iio/adc/*'
      - '.github/workflows/workflow.yml'
      - 'arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb'

jobs:
  demo-artifacts:
    runs-on: berinde_codrin_docker

    env:
      CROSS_COMPILE: arm-linux-gnueabi-
      ARCH: arm

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Produce element
        run:
          make zynq_xcomm_adv7511_defconfig

      - name: Produce uImage
        run:
          make -j14 UIMAGE_LOADADDR=0x8000 uImage

      - name: Produce device tree
        run:
          make xilinx/zynq-coraz7s-ad5592r-s.dtb

      - name: Produce artifact
        run: |
          echo "Summer Practice" > artifact.txt
          echo ${{ github.sha }} >> artifact.txt
          echo "$CROSS_COMPILE" >> artifact.txt
          echo "$ARCH" >> artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uImage
          path: arch/arm/boot/uImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devicetree.dtb
          path: arch/arm/boot/dts/xilinx/zynq-coraz7s-ad5592r-s.dtb

  demo-checkpatch:
    runs-on: berinde_codrin_docker

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Produce git command 
        run: |
          git fetch origin main
          for commit in $(git rev-list --reverse origin/main..HEAD); do
            ./scripts/checkpatch.pl --git "$commit" \
              --ignore FILE_PATH_CHANGES \
              --ignore LONG_LINE \
              --ignore LONG_LINE_STRING \
              --ignore LONG_LINE_COMMENT \
              --strict || true
          done

      - name: Produce artifact
        run: |
          echo "Summer Practice" > artifact1.txt
          echo ${{ github.sha }} >> artifact1.txt

  deploy:
    needs: demo-artifacts
    environment: summer_practice_secrets
    runs-on: berinde_codrin

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./
      - name: Display structure of downloaded files
        run: ls -l ./

      - name: Put device tree and uImage on coraz7s
        run: |
          sudo apt-get install -y sshpass
          sshpass -p '${{ secrets.berinde_codrin }}' scp -o StrictHostKeyChecking=no ./uImage/uImage root@10.76.84.22:/boot/
          sshpass -p '${{ secrets.berinde_codrin }}' scp -o StrictHostKeyChecking=no ./devicetree.dtb/zynq-coraz7s-ad5592r-s.dtb root@10.76.84.22:/boot/devicetree.dtb